name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Instala y compila proyecto
        run: |
          npm i
          npm run build
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Cerrando Servidor NODE
        run: pkill -f node || true

      - name: Coping files
        run: |
          mv dist /home/bhenzo/apps/nx_ci >  /home/bhenzo/apps/deploy_log.txt
          cd /home/bhenzo/apps/nx_ci/dist/app 
          nohup node main.js > /dev/null 2>&1 &
